baseURL = 'https://jrgochan.github.io'
languageCode = 'en-us'
title = 'jrgochan thoughts'
theme = "learn"

[params]
  author = "Jason Gochanour"
  description = "A short description."

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

[taxonomies]
  tag = "tags"
  category = "categories"

